const { Client } = require('pg');
const fs = require('fs');
const path = require('path');

const LOCATIONS_TS_PATH = "c:\\Users\\simpl\\Desktop\\SimplyMobility\\leslies-weaving-marketing\\src\\data\\locations.ts";

async function main() {
    console.log("Reading existing locations.ts to preserve CITIES array...");
    const content = fs.readFileSync(LOCATIONS_TS_PATH, 'utf8');
    
    // Extract CITIES block
    const citiesStartIdx = content.indexOf("export const CITIES");
    let keywordsStartIdx = content.indexOf("export const KEYWORDS");
    if (keywordsStartIdx === -1) {
        keywordsStartIdx = content.indexOf("const KEYWORDS");
    }
    
    if (citiesStartIdx === -1 || keywordsStartIdx === -1) {
        console.error("Could not locate CITIES or KEYWORDS in locations.ts");
        process.exit(1);
    }
    
    let citiesBlock = content.substring(citiesStartIdx, keywordsStartIdx).trim();
    if (citiesBlock.endsWith("export")) {
        citiesBlock = citiesBlock.substring(0, citiesBlock.length - 6).trim();
    }

    // Read keywords from PostgreSQL
    console.log("Loading keywords from database...");
    const POSTGRES_CONN_STRING = "postgresql://neondb_owner:npg_P7TvY0rpwLcR@ep-plain-flower-an7t5aj5-pooler.c-6.us-east-1.aws.neon.tech/leslies_seo_db?channel_binding=require&sslmode=require";
    const pgClient = new Client({ connectionString: POSTGRES_CONN_STRING });
    await pgClient.connect();
    
    let keywords = [];
    try {
        const res = await pgClient.query("SELECT keyword FROM combined_keywords ORDER BY id ASC");
        keywords = res.rows.map(r => r.keyword);
    } finally {
        await pgClient.end();
    }
    console.log(`Loaded ${keywords.length} keywords.`);

    // Generate KEYWORDS TS array definition
    console.log("Generating KEYWORDS array TypeScript code...");
    const keywordsCode = [];
    
    keywords.forEach(kw => {
        const slug = kw.toLowerCase().replace(/[^a-z0-9]+/g, "-");
        const parts = kw.split(' ');
        // Short keyword is usually the last two words, e.g. "upholstery fabric"
        const kwShort = parts.slice(1).join(' ').toLowerCase();
        
        keywordsCode.push(`  {
    keyword: "${kw}",
    keywordShort: "${kwShort}",
    slug: "${slug}",
    p1Template: (city, character, audience, state) =>
      \`\${audience} in \${city} work with some of the most discerning clients in \${state === 'FL' ? 'South Florida' : 'the region'} — clients whose homes reflect \${character}. When a project calls for ${kwShort} that no showroom carries, woven to a client's exact specification in a colorway that belongs to their home alone, Leslie's Weaving is the only studio within a thousand miles that can deliver it.\`,
    p2Template: (city, neighbors, state) =>
      \`Our 72-inch computerized Dobby loom in Coral Springs weaves 100% North American cotton ${kwShort} at 24-shaft complexity — intricate, exclusive patterns that mass-market suppliers cannot replicate. Every yard is woven by hand, inspected by hand, and shipped directly to your studio or your client's address in \${city}\${neighbors.length ? ', ' + neighbors[0] : ''}, or anywhere in \${state === 'FL' ? 'South Florida' : 'the state'}.\`,
    closingTemplate: (city, neighbors, county, state) =>
      \`Serving \${city}\${neighbors.length ? ', ' + neighbors.join(", ") : ""}, and the broader \${county} design community. \${state === 'FL' ? 'We bring the sample book to you.' : 'Consultations available online and samples shipped directly.'}\`
  }`);
    });

    const newContent = `/**
 * Programmatic SEO location data for Leslie's Weaving
 * Automatically generated by rebuild_locations_ts.js
 */

export interface LocationPage {
  slug: string;
  city: string;
  county: string;
  state: string;
  keyword: string;
  keywordShort: string;
  audience: string;
  neighbors: string[];
  bodyParagraph1: string;
  bodyParagraph2: string;
  closingSignal: string;
}

// ─── City definitions ────────────────────────────────────────────────────────
${citiesBlock}

// ─── Keyword clusters ────────────────────────────────────────────────────────
export const KEYWORDS: Array<{
  keyword: string;
  keywordShort: string;
  slug: string;
  p1Template: (city: string, character: string, audience: string, state: string) => string;
  p2Template: (city: string, neighbors: string[], state: string) => string;
  closingTemplate: (city: string, neighbors: string[], county: string, state: string) => string;
}> = [
${keywordsCode.join(',\n')}
];

// ─── Audience label helper ───────────────────────────────────────────────────
export function audienceLabel(variant: string): string {
  if (variant === "fashion") return "Fashion Designers";
  if (variant === "judaica") return "Judaica & Ceremonial Designers";
  return "Interior Designers";
}

// ─── Resolve single page dynamically on-demand ────────────────────────────────
export function getLocationPageBySlug(slug: string): LocationPage | null {
  // Sort by city name length descending so the longest city names match first
  const sortedCities = [...CITIES].sort((a, b) => b.city.length - a.city.length);
  
  for (const cityDef of sortedCities) {
    const citySlug = cityDef.city.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    if (slug.startsWith(citySlug + "-")) {
      const kwSlug = slug.substring(citySlug.length + 1);
      const kw = KEYWORDS.find(k => k.slug === kwSlug);
      if (kw) {
        const audience = audienceLabel(cityDef.audienceVariant);
        const state = cityDef.state || "FL";
        return {
          slug,
          city: cityDef.city,
          county: cityDef.county,
          state,
          keyword: kw.keyword,
          keywordShort: kw.keywordShort,
          audience,
          neighbors: cityDef.neighbors || [],
          bodyParagraph1: kw.p1Template(cityDef.city, cityDef.character, audience, state),
          bodyParagraph2: kw.p2Template(cityDef.city, cityDef.neighbors || [], state),
          closingSignal: kw.closingTemplate(cityDef.city, cityDef.neighbors || [], cityDef.county, state),
        };
      }
    }
  }
  return null;
}

export const TOTAL_LOCATION_PAGES = CITIES.length * KEYWORDS.length;
`;

    console.log("Writing rebuilt locations.ts...");
    fs.writeFileSync(LOCATIONS_TS_PATH, newContent, 'utf8');
    console.log("✓ Successfully rebuilt locations.ts.");
}

main().catch(console.error);
